#采用什么模板编写博客
github: [metadata]
#markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate

lsi: false
safe: true
source: http://www.aftermath.cn
incremental: rouge
gist:
   noscript: false

#是否有文件更新就需要更新站点
auto: true

#规定了博客的URL地址
permalink: /:title.html
url: http://www.aftermath.cn
author: vimer
email: yuzibode@126.com

#禁用自定义插件
safe: true

#分页数量
paginate: 20

#代码高亮
highlighter: rouge
comments:
    provider:duoshuo
#duoshuo:
#       short_name: yuzibo
